# --- Gateway Connection ---
gateways:
  trino:
    connection:
      # For more information on configuring the connection to your execution engine, visit:
      # https://sqlmesh.readthedocs.io/en/stable/reference/configuration/#connection
      # https://sqlmesh.readthedocs.io/en/stable/integrations/engines/trino/#connection-options
      type: trino
      host: localhost
      user: admin
      catalog: iceberg
      port: 8060
      schema_location_mapping:
        '.*': 's3://iceberg/@{schema_name}'
      http_scheme: http
      # pre_ping: False
      # pretty_sql: False
      # schema_differ_overrides: 
      # catalog_type_overrides: 
      # method: no-auth
      # port: 
      # http_scheme: https
      # roles: 
      # http_headers: 
      # session_properties: 
      # retries: 3
      # timezone: 
      # password: 
      # verify: 
      # impersonation_user: 
      # keytab: 
      # krb5_config: 
      # principal: 
      # service_name: trino
      # hostname_override: 
      # mutual_authentication: False
      # force_preemptive: False
      # sanitize_mutual_error_response: True
      # delegate: False
      # jwt_token: 
      # client_certificate: 
      # client_private_key: 
      # cert: 
      # schema_location_mapping: 
      # timestamp_mapping:
    state_connection:
      type: postgres
      host: localhost
      port: 5432
      user: ngods
      password: ngods
      database: sqlmesh_state

default_gateway: trino

# --- Model Defaults ---
# https://sqlmesh.readthedocs.io/en/stable/reference/model_configuration/#model-defaults

model_defaults:
  dialect: trino
  start: 2025-12-23 # Start date for backfill history
  cron: '@daily'    # Run models daily at 12am UTC (can override per model)

# --- Linting Rules ---
# Enforce standards for your team
# https://sqlmesh.readthedocs.io/en/stable/guides/linter/

linter:
  enabled: true
  rules:
    - ambiguousorinvalidcolumn
    - invalidselectstarexpansion
    - noambiguousprojections

project: team_a